sudo: required

language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - script: make build-alpine
    - script: make build-debian
    - stage: publish
      script: echo "publishing...."
      deploy:
        - provider: script
          script: make publish
          on:
            branch: master

        - provider: script
          script: make publish
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v.*$
